name: StudioGix
favicon: null
layout_spectrum: 0.49548
typography_spectrum: 0.56713
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#04121d'
    - '#97ffff'
    - '#3475af'
    - '#e9758b'
    - '#ffbfbd'
  brandStrength: 1
  lightness: 0.25
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
